apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose.yaml
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: items-service
  name: items-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: items-service
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose.yaml
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.network/microservices: "true"
        io.kompose.service: items-service
    spec:
      containers:
        - image: items-service:v1
          name: items-service
          ports:
            - containerPort: 8081
          resources: {}
      restartPolicy: Always
status: {}
