apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose.yaml
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: mysqlhost
  name: mysqlhost
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mysqlhost
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose.yaml
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.network/microservices: "true"
        io.kompose.service: mysqlhost
    spec:
      containers:
        - env:
            - name: MYSQL_DATABASE
              value: productdb
            - name: MYSQL_ROOT_PASSWORD
              value: "1234"
          image: mysql:8
          name: mysqlhost
          ports:
            - containerPort: 3306
          resources: {}
      restartPolicy: Always
status: {}
